---
sudo: false
language: node_js
cache: yarn

node_js:
- '8'
- '6'
- '4'

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.0
- export PATH=$HOME/.yarn/bin:$PATH

before_script:
- yarn build

script:
- if [ -n "${LINT-}" ]; then yarn lint; fi
- if [ -z "${SKIPTESTS-}" ]; then yarn cover; fi

after_script:
- codeclimate-test-reporter < coverage/lcov.info

matrix:
  include:
    - node_js: "node"
      env: LINT=true SKIPTESTS=true

addons:
  code_climate:
    repo_token:
      secure: hU3p2PlR6A4ZdTDzkYsKpXbuFsgdgSTDBW+b+SSs7ePpz1hbY86oYCP6SLNB87qMwM97oFae21/mGGQhrwc6lQiDNNYLM5C4twypjHk1sbXfyCtIOvJI9EjlxqOtPy1/FJ7jzeCSm9zts/r7IhNrEJpvA8Usg8hX9agI1W2Wy006sKplmhE7WNIhr9iikkhMVlIftWy4/nWDDQ66DiRh526VMi5ruv8jp22zeH3Nj6DrE3pCfj6+NXbNLYuP7KqGRDN9WWUrVOSHGwa215SOP9GYocNXoqhdgbWiestMpyj3GLOfHAqitw7Sdem9+yyPf1x9cMfuSYLddjIGEhLo6AE5KjjI86njycX2/di8ykMNXyevZEuKN3W7rcuVW817FC7ehEpjPphPHTsuku8nwtJlGSgCbNWffq+k+kc421Nm92TAWkdIBtqaG2dX6pBE420BaMNlT7FxqEDznzWuKbFh+Hcdx7RHbfJbWfAJEvztGEN6jKLjSq+T58d6Q6PSs1pjUxe/wPrw9oksem6lKGNxzlbV2/89WSfU5p57NBOlIuTr3Tt5//PlHeStgeVNWF/zkJQzqk8DnE38fD+EALX7sU8kirO2gtD71F7ZzuDZ06agPQoM7hgtDBaKt/GC4OZsxVli8MZlG80yPXaIe8E3tpxYSG7Uw4bPQSGM3xc=
